import React, { useState, useEffect } from 'react';
import { 
  Settings, 
  ChevronDown, 
  ArrowLeftRight, 
  Download, 
  Copy, 
  Lightbulb, 
  Globe,
  Info,
  BookOpen,
  Check,
  ExternalLink
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export default function App() {
  const [inputText, setInputText] = useState('');
  const [outputText, setOutputText] = useState('');
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [copied, setCopied] = useState(false);
  const [itemCount, setItemCount] = useState(0);

  useEffect(() => {
    const lines = inputText.split('\n').filter(line => line.trim().length > 0);
    setItemCount(lines.length);
    
    if (lines.length > 0) {
      generateConfig(lines);
    } else {
      setOutputText('');
    }
  }, [inputText]);

  const generateConfig = (links: string[]) => {
    const config = `# Clash Meta Configuration
# Generated by Clash Converter
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: :9090

proxies:
${links.map(link => {
  try {
    const url = new URL(link);
    const name = decodeURIComponent(url.hash.slice(1)) || `Proxy-${Math.random().toString(36).slice(2, 7)}`;
    return `  - name: ${name}\n    type: ${url.protocol.replace(':', '')}\n    server: ${url.hostname}\n    port: ${url.port || 443}`;
  } catch {
    return `  # Invalid link: ${link}`;
  }
}).join('\n')}

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
${links.map(link => {
  try {
    const url = new URL(link);
    return `      - ${decodeURIComponent(url.hash.slice(1)) || 'Unknown'}`;
  } catch { return null; }
}).filter(Boolean).join('\n')}

rules:
  - DOMAIN-SUFFIX,google.com,Proxy
  - DOMAIN-KEYWORD,google,Proxy
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy`;
    
    setOutputText(config);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(outputText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([outputText], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "config.yaml";
    document.body.appendChild(element);
    element.click();
  };

  return (
    <div className="relative min-h-screen p-4 md:p-8 font-sans">
      {/* Background Blobs */}
      <div className="blob w-[400px] h-[400px] bg-purple-400 top-[-100px] left-[-100px]" />
      <div className="blob w-[300px] h-[300px] bg-blue-400 bottom-[10%] right-[10%]" />
      <div className="blob w-[250px] h-[250px] bg-pink-400 top-[40%] left-[20%]" />

      <div className="max-w-6xl mx-auto relative z-10">
        {/* Navbar */}
        <header className="neo-card px-6 py-3 mb-12 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-white font-bold text-lg">
              C
            </div>
            <h1 className="text-xl font-semibold text-slate-800 flex items-center gap-1">
              Clash Converter <Settings size={18} className="text-slate-400 cursor-pointer hover:text-slate-600 transition-colors" />
            </h1>
          </div>

          <div className="hidden md:flex items-center gap-4">
            <button className="neo-button px-5 py-2 text-sm font-medium flex items-center gap-2">
              <BookOpen size={16} /> Resources
            </button>
            <button className="neo-button px-5 py-2 text-sm font-medium flex items-center gap-2">
              <Info size={16} /> About
            </button>
            <div className="neo-button px-4 py-2 text-sm font-medium flex items-center gap-2 cursor-pointer">
              <Globe size={16} /> English <ChevronDown size={14} />
            </div>
            <div 
              className={`w-14 h-7 rounded-full p-1 cursor-pointer transition-colors duration-300 ${isDarkMode ? 'bg-slate-700' : 'bg-lavender-200'}`}
              onClick={() => setIsDarkMode(!isDarkMode)}
              style={{ boxShadow: 'inset 2px 2px 5px rgba(0,0,0,0.1)' }}
            >
              <motion.div 
                className="w-5 h-5 bg-white rounded-full shadow-sm"
                animate={{ x: isDarkMode ? 28 : 0 }}
              />
            </div>
          </div>
        </header>

        {/* Main Content */}
        <main className="grid grid-cols-1 lg:grid-cols-[1fr_auto_1fr] items-center gap-8">
          {/* Input Card */}
          <section className="neo-card p-8 flex flex-col gap-6 h-[600px]">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold text-slate-800">Input</h2>
              <div className="neo-button px-4 py-2 text-sm font-medium flex items-center gap-2 cursor-pointer">
                Proxy Links <ChevronDown size={14} />
              </div>
            </div>

            <div className="neo-inset flex-1 p-6 relative flex flex-col">
              <textarea
                className="w-full h-full bg-transparent resize-none outline-none text-slate-600 font-mono text-sm placeholder:text-slate-400"
                placeholder="Paste your proxy links here - one per line&#10;&#10;hysteria://...&#10;vmess://...&#10;vmess://...&#10;sctions://...&#10;vmess://...&#10;etc://..."
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
              />
              <div className="mt-4 flex items-center gap-2 text-xs text-slate-400">
                <Lightbulb size={14} className="text-amber-400" />
                <span>Tip · Paste your proxy links here - one per line</span>
              </div>
            </div>

            <div className="text-right text-sm text-slate-400 font-medium">
              {itemCount} item(s) found
            </div>
          </section>

          {/* Swap Button */}
          <div className="flex justify-center">
            <button className="neo-button w-16 h-16 flex flex-col items-center justify-center gap-1 group">
              <ArrowLeftRight className="text-slate-500 group-hover:rotate-180 transition-transform duration-500" />
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Swap</span>
            </button>
          </div>

          {/* Output Card */}
          <section className="neo-card p-8 flex flex-col gap-6 h-[600px]">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold text-slate-800">Output</h2>
              <div className="neo-button px-4 py-2 text-sm font-medium flex items-center gap-2 cursor-pointer">
                Clash Meta <ChevronDown size={14} />
              </div>
            </div>

            <div className="neo-inset flex-1 p-6 relative flex flex-col">
              <textarea
                readOnly
                className="w-full h-full bg-transparent resize-none outline-none text-slate-600 font-mono text-sm placeholder:text-slate-400"
                placeholder="# Your Clash config will appear here"
                value={outputText}
              />
              <div className="mt-4 flex items-center gap-2 text-xs text-slate-400">
                <Settings size={14} />
                <span>Shadow-clayPressed</span>
              </div>
            </div>

            <div className="flex gap-4">
              <button 
                onClick={handleDownload}
                disabled={!outputText}
                className="flex-1 neo-button py-3 bg-gradient-to-r from-indigo-500 to-purple-500 text-white font-bold flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Download size={18} /> Download
              </button>
              <button 
                onClick={handleCopy}
                disabled={!outputText}
                className="flex-1 neo-button py-3 text-slate-700 font-bold flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {copied ? <Check size={18} className="text-green-500" /> : <Copy size={18} />} 
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </section>
        </main>

        {/* Footer */}
        <footer className="mt-16 text-center text-slate-400 text-sm flex flex-col gap-2">
          <p>© 2026 Clash Converter. All rights reserved.</p>
          <div className="flex items-center justify-center gap-4">
            <a href="#" className="hover:text-purple-500 transition-colors">Privacy Policy</a>
            <a href="#" className="hover:text-purple-500 transition-colors">Terms of Service</a>
            <a href="#" className="hover:text-purple-500 transition-colors flex items-center gap-1">
              GitHub <ExternalLink size={12} />
            </a>
          </div>
        </footer>
      </div>
    </div>
  );
}
